### ISSUE TITLE
Error when using a data path for Static value (B)

### ISSUE THREAD

**Issue by Koalahund** [BadIdeasBureau/memento-mori#4]
Throws an error when using a data path for Static value (B) in the settings
Working fine while using a static number.
![db9536246cf9f91106d9531082f449e6](https://user-images.githubusercontent.com/85458282/150799497-320214fc-39a3-4cdc-b75b-68beb9efd243.png)

**Comment by BadIdeasBureau** [comment]
Update the module, and it should work - it's a simple fix that I could do quickly while at work, but that does mean I've not tested it yet so you're kind of a guinea pig here!

(one day, I will get the syntax for getProperty() right first time and/or remember to test the bits of my modules that I don't use personally)

**Comment by Koalahund** [comment]
Seems fixed with the new update.
Thanks :)
