### ISSUE TITLE
This awesome module doesn't appear to be working with Foundry 11.313

### ISSUE THREAD

**Issue by Stormthirst** [BadIdeasBureau/memento-mori#8]
This awesome module doesn't appear to be working with Foundry 11.313

**Comment by davidhawbecker** [comment]
Bump

**Comment by BadIdeasBureau** [comment]
Updated for v11 - sorry for the delay!

**Comment by davidhawbecker** [comment]
Already downloaded and back in my game. Love this little mod. Thank you.
